# Generated by Django 3.1 on 2020-09-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beach',
            name='driving_dist',
        ),
        migrations.AlterField(
            model_name='beach',
            name='swell1_period',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beach',
            name='swell2_period',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Surfer',
        ),
    ]
