# Generated by Django 3.1 on 2020-09-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20200904_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beach',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='beach',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='beach',
            name='swell1_height',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='beach',
            name='swell2_height',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='beach',
            name='tide_height',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='beach',
            name='water_temp',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
    ]
